---
- name: Check agent pinned version on Windows
  ansible.builtin.fail:
    msg: "The Agent versions you pinned (6.14.0 or 6.14.1) have been blacklisted, please use 6.14.2 instead. See https://dtdg.co/win-614-fix."
  when: datadog_agent_version == "6.14.0" or datadog_agent_version == "6.14.1"

- name: Set agent download filename to a specific version
  ansible.builtin.set_fact:
    agent_dd_download_url: "{{ datadog_windows_versioned_url }}-{{ agent_datadog_agent_windows_version }}.msi"
