---
# This file doesn't actually contain "handlers" in the Ansible sense: when running
# our role, Ansible only loads the contents of handlers/main.yml as handlers.
# However, this is here because this is a "handler-like" task that is dynamically
# included by a handler task in handlers/main.yml.

- name: Restart datadog-agent service
  command: "launchctl kickstart -k system/{{ macos_user_id.stdout }}/{{ datadog_macos_service_name }}"
  register: command_result
  check_mode: no
  when: datadog_enabled and not ansible_check_mode and ansible_facts.os_family == "Darwin"
